# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: Baccarat.proto for package 'net.gurigoro.kaiji.baccarat'

require 'grpc'
require_relative './Baccarat_pb'

module Net
  module Gurigoro
    module Kaiji
      module Baccarat
        module Baccarat
          class Service

            include GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'net.gurigoro.kaiji.baccarat.Baccarat'

            rpc :CreateNewGameRoom, CreateNewGameRoomRequest, CreateNewGameRoomReply
            rpc :Bet, BetRequest, BetReply
            rpc :StartOpeningCards, StartOpeningCardsRequest, StartOpeningCardsReply
            rpc :GetGameResult, GetGameResultRequest, GetGameResultReply
            rpc :DestroyGameRoom, DestroyGameRoomRequest, DestroyGameRoomReply
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
