# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Baccarat.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "net.gurigoro.kaiji.baccarat.CreateNewGameRoomRequest" do
    optional :accessToken, :string, 1
    repeated :usersId, :int64, 2
  end
  add_message "net.gurigoro.kaiji.baccarat.CreateNewGameRoomReply" do
    optional :isSucceed, :bool, 1
    optional :gameRoomId, :int64, 2
  end
  add_message "net.gurigoro.kaiji.baccarat.BetRequest" do
    optional :accessToken, :string, 1
    optional :gameRoomId, :int64, 2
    optional :userId, :int64, 3
    optional :betPoints, :int64, 4
    optional :bettingSide, :enum, 5, "net.gurigoro.kaiji.baccarat.BetSide"
  end
  add_message "net.gurigoro.kaiji.baccarat.BetReply" do
    optional :result, :enum, 1, "net.gurigoro.kaiji.baccarat.BettingResult"
    optional :userId, :int64, 2
  end
  add_message "net.gurigoro.kaiji.baccarat.StartOpeningCardsRequest" do
    optional :accessToken, :string, 1
    optional :gameRoomId, :int64, 2
  end
  add_message "net.gurigoro.kaiji.baccarat.StartOpeningCardsReply" do
    optional :result, :enum, 1, "net.gurigoro.kaiji.baccarat.StartOpeningCardsReply.StartOpeningCardsResult"
    optional :wonSide, :enum, 2, "net.gurigoro.kaiji.baccarat.BetSide"
  end
  add_enum "net.gurigoro.kaiji.baccarat.StartOpeningCardsReply.StartOpeningCardsResult" do
    value :SUCCEED, 0
    value :NOT_ALL_USERS_BETTED_YET, 1
    value :UNKNOWN_FAILED, 2
  end
  add_message "net.gurigoro.kaiji.baccarat.GetGameResultRequest" do
    optional :accessToken, :string, 1
    optional :gameRoomId, :int64, 2
  end
  add_message "net.gurigoro.kaiji.baccarat.PlayerResult" do
    optional :userId, :int64, 1
    optional :gameResult, :enum, 2, "net.gurigoro.kaiji.baccarat.PlayerResult.GameResult"
    optional :gotPoints, :int64, 3
  end
  add_enum "net.gurigoro.kaiji.baccarat.PlayerResult.GameResult" do
    value :LOSE, 0
    value :WIN, 1
    value :TIE, 2
  end
  add_message "net.gurigoro.kaiji.baccarat.GetGameResultReply" do
    optional :result, :enum, 1, "net.gurigoro.kaiji.baccarat.GetGameResultReply.GetGameRequestResult"
    repeated :playerResults, :message, 2, "net.gurigoro.kaiji.baccarat.PlayerResult"
  end
  add_enum "net.gurigoro.kaiji.baccarat.GetGameResultReply.GetGameRequestResult" do
    value :SUCCEED, 0
    value :NOT_OPENED_CARDS_YET, 1
    value :UNKNOWN_FAILED, 2
  end
  add_message "net.gurigoro.kaiji.baccarat.DestroyGameRoomRequest" do
    optional :accessToken, :string, 1
    optional :gameRoomId, :int64, 2
  end
  add_message "net.gurigoro.kaiji.baccarat.DestroyGameRoomReply" do
    optional :isSucceed, :bool, 1
  end
  add_enum "net.gurigoro.kaiji.baccarat.BetSide" do
    value :PLAYER, 0
    value :BANKER, 1
    value :TIE, 2
  end
  add_enum "net.gurigoro.kaiji.baccarat.BettingResult" do
    value :SUCCEED, 0
    value :NO_ENOUGH_POINTS, 1
    value :UNKNOWN_FAILED, 2
  end
end

module Net
  module Gurigoro
    module Kaiji
      module Baccarat
        CreateNewGameRoomRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.baccarat.CreateNewGameRoomRequest").msgclass
        CreateNewGameRoomReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.baccarat.CreateNewGameRoomReply").msgclass
        BetRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.baccarat.BetRequest").msgclass
        BetReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.baccarat.BetReply").msgclass
        StartOpeningCardsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.baccarat.StartOpeningCardsRequest").msgclass
        StartOpeningCardsReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.baccarat.StartOpeningCardsReply").msgclass
        StartOpeningCardsReply::StartOpeningCardsResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.baccarat.StartOpeningCardsReply.StartOpeningCardsResult").enummodule
        GetGameResultRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.baccarat.GetGameResultRequest").msgclass
        PlayerResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.baccarat.PlayerResult").msgclass
        PlayerResult::GameResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.baccarat.PlayerResult.GameResult").enummodule
        GetGameResultReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.baccarat.GetGameResultReply").msgclass
        GetGameResultReply::GetGameRequestResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.baccarat.GetGameResultReply.GetGameRequestResult").enummodule
        DestroyGameRoomRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.baccarat.DestroyGameRoomRequest").msgclass
        DestroyGameRoomReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.baccarat.DestroyGameRoomReply").msgclass
        BetSide = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.baccarat.BetSide").enummodule
        BettingResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.baccarat.BettingResult").enummodule
      end
    end
  end
end
