# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blackjack.proto

require 'google/protobuf'

require 'trump_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "net.gurigoro.kaiji.CreateNewGameRoomRequest" do
    optional :accessToken, :string, 1
    repeated :usersId, :int64, 2
  end
  add_message "net.gurigoro.kaiji.CreateNewGameRoomReply" do
    optional :isSucceed, :bool, 1
    optional :gameRoomId, :int64, 2
  end
  add_message "net.gurigoro.kaiji.BettingRequest" do
    optional :accessToken, :string, 1
    optional :gameRoomId, :int64, 2
    optional :userId, :int64, 3
    optional :betPoints, :int64, 4
  end
  add_message "net.gurigoro.kaiji.BettingReply" do
    optional :result, :enum, 1, "net.gurigoro.kaiji.BettingReply.BettingResult"
    optional :userId, :int64, 2
  end
  add_enum "net.gurigoro.kaiji.BettingReply.BettingResult" do
    value :SUCCEED, 0
    value :NO_ENOUGH_POINTS, 1
    value :ALREADY_BETTED, 2
    value :UNKNOWN_FAILED, 3
  end
  add_message "net.gurigoro.kaiji.FirstDealPlayerCards" do
    optional :userId, :int64, 1
    optional :cards, :message, 2, "net.gurigoro.kaiji.TrumpCards"
  end
  add_message "net.gurigoro.kaiji.SetFirstDealedCardsRequest" do
    optional :accessToken, :string, 1
    optional :gameRoomId, :int64, 2
    repeated :playerCards, :message, 3, "net.gurigoro.kaiji.FirstDealPlayerCards"
  end
  add_message "net.gurigoro.kaiji.AllowedPlayerActions" do
    optional :userId, :int64, 1
    optional :cardPoints, :int64, 2
    repeated :actions, :enum, 3, "net.gurigoro.kaiji.PlayerAction"
  end
  add_message "net.gurigoro.kaiji.SetFirstDealedCardsReply" do
    optional :isSucceed, :bool, 1
    repeated :actions, :message, 2, "net.gurigoro.kaiji.AllowedPlayerActions"
  end
  add_message "net.gurigoro.kaiji.SetFirstDealersCardRequest" do
    optional :accessToken, :string, 1
    optional :gameRoomId, :int64, 2
    optional :card, :message, 3, "net.gurigoro.kaiji.TrumpCard"
  end
  add_message "net.gurigoro.kaiji.SetFirstDealersCardReply" do
    optional :isSucceed, :bool, 1
  end
  add_message "net.gurigoro.kaiji.HitRequest" do
    optional :accessToken, :string, 1
    optional :gameRoomId, :int64, 2
    optional :userId, :int64, 3
    optional :card, :message, 4, "net.gurigoro.kaiji.TrumpCard"
    optional :handsIndex, :int64, 5
  end
  add_message "net.gurigoro.kaiji.HitReply" do
    optional :isSucceed, :bool, 1
    optional :userId, :int64, 2
    optional :isBusted, :bool, 3
    optional :cardPoints, :int64, 4
    repeated :allwedActions, :enum, 5, "net.gurigoro.kaiji.PlayerAction"
  end
  add_message "net.gurigoro.kaiji.StandRequest" do
    optional :accessToken, :string, 1
    optional :gameRoomId, :int64, 2
    optional :userId, :int64, 3
    optional :handsIndex, :int64, 4
  end
  add_message "net.gurigoro.kaiji.StandReply" do
    optional :isSucceed, :bool, 1
  end
  add_message "net.gurigoro.kaiji.SplitRequest" do
    optional :accessToken, :string, 1
    optional :gameRoomId, :int64, 2
    optional :userId, :int64, 3
  end
  add_message "net.gurigoro.kaiji.SplitReply" do
    optional :isSucceed, :bool, 1
  end
  add_message "net.gurigoro.kaiji.DoubleDownRequest" do
    optional :accessToken, :string, 1
    optional :gameRoomId, :int64, 2
    optional :userId, :int64, 3
  end
  add_message "net.gurigoro.kaiji.DoubleDownReply" do
    optional :isSucceed, :bool, 1
    optional :userId, :int64, 2
    optional :isBusted, :bool, 3
    optional :cardPoints, :int64, 4
  end
  add_message "net.gurigoro.kaiji.SetNextDealersCardRequest" do
    optional :accessToken, :string, 1
    optional :gameRoomId, :int64, 2
    optional :card, :message, 3, "net.gurigoro.kaiji.TrumpCard"
  end
  add_message "net.gurigoro.kaiji.SetNextDealersCardReply" do
    optional :isSucceed, :bool, 1
    optional :cardPoints, :int64, 2
    optional :shouldHit, :bool, 3
    optional :isBusted, :bool, 4
  end
  add_message "net.gurigoro.kaiji.GetGameResultRequest" do
    optional :accessToken, :string, 1
    optional :gameRoomId, :int64, 2
  end
  add_message "net.gurigoro.kaiji.PlayerResult" do
    optional :userId, :int64, 1
    optional :gameResult, :enum, 2, "net.gurigoro.kaiji.PlayerResult.GameResult"
    optional :gotPoints, :int64, 3
  end
  add_enum "net.gurigoro.kaiji.PlayerResult.GameResult" do
    value :LOSE, 0
    value :TIE, 1
    value :WIN, 2
  end
  add_message "net.gurigoro.kaiji.GetGameResultReply" do
    optional :isSucceed, :bool, 1
    repeated :playerResults, :message, 2, "net.gurigoro.kaiji.PlayerResult"
  end
  add_message "net.gurigoro.kaiji.DestroyGameRoomRequest" do
    optional :accessToken, :string, 1
    optional :gameRoomId, :int64, 2
  end
  add_message "net.gurigoro.kaiji.DestroyGameRoomReply" do
    optional :isSucceed, :bool, 1
  end
  add_enum "net.gurigoro.kaiji.PlayerAction" do
    value :UNKNOWN, 0
    value :HIT, 1
    value :STAND, 2
    value :SPLIT, 3
    value :DOUBLEDOWN, 4
  end
end

module Net
  module Gurigoro
    module Kaiji
      CreateNewGameRoomRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.CreateNewGameRoomRequest").msgclass
      CreateNewGameRoomReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.CreateNewGameRoomReply").msgclass
      BettingRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.BettingRequest").msgclass
      BettingReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.BettingReply").msgclass
      BettingReply::BettingResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.BettingReply.BettingResult").enummodule
      FirstDealPlayerCards = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.FirstDealPlayerCards").msgclass
      SetFirstDealedCardsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.SetFirstDealedCardsRequest").msgclass
      AllowedPlayerActions = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.AllowedPlayerActions").msgclass
      SetFirstDealedCardsReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.SetFirstDealedCardsReply").msgclass
      SetFirstDealersCardRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.SetFirstDealersCardRequest").msgclass
      SetFirstDealersCardReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.SetFirstDealersCardReply").msgclass
      HitRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.HitRequest").msgclass
      HitReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.HitReply").msgclass
      StandRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.StandRequest").msgclass
      StandReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.StandReply").msgclass
      SplitRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.SplitRequest").msgclass
      SplitReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.SplitReply").msgclass
      DoubleDownRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.DoubleDownRequest").msgclass
      DoubleDownReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.DoubleDownReply").msgclass
      SetNextDealersCardRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.SetNextDealersCardRequest").msgclass
      SetNextDealersCardReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.SetNextDealersCardReply").msgclass
      GetGameResultRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.GetGameResultRequest").msgclass
      PlayerResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.PlayerResult").msgclass
      PlayerResult::GameResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.PlayerResult.GameResult").enummodule
      GetGameResultReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.GetGameResultReply").msgclass
      DestroyGameRoomRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.DestroyGameRoomRequest").msgclass
      DestroyGameRoomReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.DestroyGameRoomReply").msgclass
      PlayerAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.PlayerAction").enummodule
    end
  end
end
