# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: blackjack.proto for package 'net.gurigoro.kaiji.blackjack'

require 'grpc'
require 'blackjack_pb'

module Net
  module Gurigoro
    module Kaiji
      module Blackjack
        module BlackJack
          class Service

            include GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'net.gurigoro.kaiji.blackjack.BlackJack'

            rpc :CreateNewGameRoom, CreateNewGameRoomRequest, CreateNewGameRoomReply
            rpc :Betting, BettingRequest, BettingReply
            rpc :SetFirstDealedCards, SetFirstDealedCardsRequest, SetFirstDealedCardsReply
            rpc :SetFirstDealersCard, SetFirstDealersCardRequest, SetFirstDealersCardReply
            rpc :Hit, HitRequest, HitReply
            rpc :Stand, StandRequest, StandReply
            rpc :Split, SplitRequest, SplitReply
            rpc :DoubleDown, DoubleDownRequest, DoubleDownReply
            rpc :SetNextDealersCard, SetNextDealersCardRequest, SetNextDealersCardReply
            rpc :GetGameResult, GetGameResultRequest, GetGameResultReply
            rpc :DestroyGameRoom, DestroyGameRoomRequest, DestroyGameRoomReply
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
