# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: point.proto for package 'net.gurigoro.kaiji'

require 'grpc'
require 'point_pb'

module Net
  module Gurigoro
    module Kaiji
      module Point
        class Service

          include GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'net.gurigoro.kaiji.Point'

          rpc :GetPointBalance, GetPointBalanceRequest, GetPointBalanceReply
          rpc :AddPoint, AddPointRequest, AddPointReply
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
