# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trump.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "net.gurigoro.kaiji.TrumpCard" do
    optional :suit, :enum, 1, "net.gurigoro.kaiji.CardSuit"
    optional :number, :int64, 2
  end
  add_message "net.gurigoro.kaiji.TrumpCards" do
    repeated :cards, :message, 1, "net.gurigoro.kaiji.TrumpCard"
  end
  add_enum "net.gurigoro.kaiji.CardSuit" do
    value :SPADE, 0
    value :CLUB, 1
    value :HEART, 2
    value :DIAMOND, 3
  end
end

module Net
  module Gurigoro
    module Kaiji
      TrumpCard = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.TrumpCard").msgclass
      TrumpCards = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.TrumpCards").msgclass
      CardSuit = Google::Protobuf::DescriptorPool.generated_pool.lookup("net.gurigoro.kaiji.CardSuit").enummodule
    end
  end
end
