FROM ruby

COPY . /app/

RUN set -x && \
    gem install bundler

CMD set -x && cd /app && bundle install --without test --without http && bundle exec rake create &&  bundle exec rake migrate && ruby /app/main.rb
