db:
  production:
    adapter:  mysql2
    host:     localhost
    username: kaiji
    password: Kaiji_1257
    database: kaiji
  development:
    adapter:  mysql2
    host:     localhost
    username: kaiji
    password: Kaiji_1257
    database: kaiji
