db:
  production:
    adapter:  mysql2
    host:     game-database
    username: root
    password: kaiji
    database: kaiji
  development:
    adapter:  mysql2
    host:     game-database
    username: root
    password: kaiji
    database: kaiji
