db:
  production:
    adapter:  mysql2
    host:     localhost
    username: kaiji
    password: Kaiji_1257
    database: kaiji
  development:
    adapter:  mysql2
    host:     mysql
    username: root
    password: kaiji
    database: kaiji
